version: '3'

services:
  mariadb:
    build: ./mariadb/
    image: eurasia36/mariadb:latest
    volumes: 
    - ./.mysql_data:/var/lib/mysql
  payara:
    image: eurasia36/payara-apps:latest
    volumes:
    - ./.payara_config:/opt/payara5/glassfish/domains/domain1/docker-config
    links:
    - mariadb
    ports:
    - 4848:4848
  httpd:
    image: eurasia36/httpd-apps:latest
    links:
    - payara
    ports:
    - 80:80
    - 443:443
