version: '3'

services:
  mariadb:
    image: eurasia36/mariadb:latest
    volumes: 
    - ./.mysql_data:/var/lib/mysql
  payara:
    image: eurasia36/payara-apps:latest
    volumes:
    - ./.payara_config:/opt/payara5/glassfish/domains/domain1/docker-config
    links:
    - mariadb
    ports:
    - 4848:4848
  httpd:
    image: eurasia36/httpd-apps:latest
    links:
    - payara
    volumes:
    - ./.httpd_data/leads:/var/www/eurasia36_kz/leads
    - ./.pki/private/STAR_eurasia36_kz-key.pem:/etc/pki/tls/private/STAR_eurasia36_kz-key.pem
    - ./.pki/certs/STAR_eurasia36_kz-chain.pem:/etc/pki/tls/certs/STAR_eurasia36_kz-chain.pem
    - ./.pki/private/eurasia36_kz-key.pem:/etc/pki/tls/private/eurasia36_kz-key.pem
    - ./.pki/certs/eurasia36_kz-chain.pem:/etc/pki/tls/certs/eurasia36_kz-chain.pem
    environment:
    - EURASIA36_WS_URL=https://payara:8181/
    - EURASIA36_WS_USER=admin
    - EURASIA36_WS_PASSWORD=admin
    ports:
    - 80:80
    - 443:443
