CREATE DATABASE IF NOT EXISTS insurance DEFAULT CHARACTER SET 'utf8';
CREATE DATABASE IF NOT EXISTS epayment DEFAULT CHARACTER SET 'utf8';
CREATE DATABASE IF NOT EXISTS eurasia DEFAULT CHARACTER SET 'utf8';

GRANT ALL ON *.* TO 'eurasia36'@'%';

FLUSH PRIVILEGES;
